### ISSUE TITLE
Custom Module System

### ISSUE THREAD

**Issue by michaelgira23** [michaelgira23/MyMICDS-v2#12]
In the homepage, allow the user to configure grid and the modules the way _they_ want to. Create a drag and drop interface to customize the modules, create an interface to easily add modules into the system, and add more modules to the system.

For storing modules in the database, it would also be nice if each module could also store user-specific settings or data. (Metric or imperial for weather, what format to display date, etc.)

**Comment by MiningPotatoes** [comment]
Started in https://github.com/michaelgira23/MyMICDS-v2/commit/80eb3ec901b0e51b25f0d1492e55b42ea4bfe047.

**Comment by MiningPotatoes** [comment]
Finished in https://github.com/michaelgira23/MyMICDS-v2/commit/702a46a6c7279883321bb4922a5fbe9b53ab03c5.

**Comment by AsianPsychoBoy** [comment]
are we including the front modules in this issue too? if so, we might want to reopen this. 
so the way i am going to do the modules is have a container component that imports all the module components, then use ComponentFactoryResolver to create them according to the backend data
