### ISSUE TITLE
Convert to ES6 syntax

### ISSUE THREAD

**Issue by MiningPotatoes** [michaelgira23/MyMICDS-v2#25]
As of right now, a majority of the back-end is written entirely in ES5 syntax. While there's nothing inherently bad about this, there are some things that can be expressed much more concisely in ES6, namely arrow functions (`e => e.something` vs `function(e) { return e.something; }`) and `for..of` loops (`for(let e of arr)` vs `for(var i = 0; i < arr.length; i++) { var e = arr[i]; }`). Lucky for us, Node has natively supported ES6 for a while now, so there's no reason not to switch.

**Comment by MiningPotatoes** [comment]
AFAIK, all of the `for..of` loop conversion was finished in https://github.com/michaelgira23/MyMICDS-v2/commit/d57e992fa8ab6ecfd167004c65ead50fd1a55d92. Still TODO is `{object: object, shorthand: shorthand}` → `{object, shorthand}`.

**Comment by michaelgira23** [comment]
This NPM module [`5to6`](https://www.npmjs.com/package/5to6) looks promising. It looks like it's able to do just that.
