### ISSUE TITLE
Fix "Block X +" prefix when not really wanted

### ISSUE THREAD

**Issue by michaelgira23** [michaelgira23/MyMICDS-v2#29]
So, the schedule works by retrieving the user's portal calendar, then adding our own classes to add stuff like lunch and free periods. If the user has a free period in the block which determines your lunch period, then we have to do something special.

Since neither lunch nor free periods show up on the portal feed, there's no way to exactly determine if the user has first or second lunch. In this case, we should display "Block X + Lunch" so we at least acknowledge the presence of that block.

The schedule works by getting the user's grade, then looking up the generic block schedule for the user's grade. It then fetches the portal feed (which contains only core classes + advisory stuff) and overlays it on-top of the generic block schedule. The generic block schedule spans both first and second lunch, so the user's portal class should ideally overlap the first half if they have second lunch, and the second half if they have first lunch. We detect if this big lunch period in the generic schedule has been overlapped. If not, then we append "Block X +" to the lunch period because that implies the user has a free period, which is *not* included in the portal feed.

Apparently, somewhere it's detecting the lunch period not being overlapped even when it is, and recursively appending that "Block X +" during certain days. I _think_ the unnecessary block prefixing is caused by users who legitimately have the prefix, but doesn't get erased so it shows up for everyone and doesn't get erased (until we restart the back-end server).

**Comment by MiningPotatoes** [comment]
I'm going to try to fix this by getting rid of the prefix thing entirely. It turns out that free periods and study halls *always* have first lunch, so splitting apart the free period and the lunch should fix it.
